# Generated by Django 4.0.5 on 2022-06-24 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('expenses', models.FloatField(default=0)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('monthly_amount', models.FloatField()),
                ('day_expense', models.FloatField()),
                ('expense_type', models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Inurance', 'Inurance'), ('Food', 'Food'), ('Entertainment', 'Enterainment'), ('Loan', 'Loan'), ('Taxes', 'Taxes'), ('Saving or Investments', 'Saving or Investments'), ('Gifts and Donations', 'Gifts and Donations'), ('Personal Care', 'Personal Care'), ('Legal', 'Legal')], max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'Expense',
            },
        ),
    ]
