# Generated by Django 4.0.5 on 2022-06-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='day_expense',
        ),
    ]
